language: ruby
bundler_args: --without development
before_install:
  - gem install bundler
  - gem update --system

matrix:
  include:
    - rvm: 2.2.10
    - rvm: 2.3.8
    - rvm: 2.4.10
    - rvm: 2.5.8
    - rvm: 2.6.9
    - rvm: 2.7.5
    - rvm: 3.0.3
    - rvm: 3.1.0
    - rvm: 3.2.0
    - rvm: 3.3.0
    - rvm: jruby-9.2.19.0
    - rvm: jruby-9.3.3.0
    - jruby-head
    - mruby
    - rubinius
    - ree

      env:
        - JRUBY_OPTS="--server -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -J-Xms512m -J-Xmx1024m"
    - rvm: ruby-head

branches:
  only:
    - master
