language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-18mode
  - rbx-19mode
  - ree
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: ree
    - rvm: 1.8.7
    - rvm: 1.9.2
    - rvm: rbx-18mode
    - rvm: rbx-19mode
branches:
  only:
    - master
