language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.0
  - ruby-head
  - jruby-head
  - rbx
  - ree
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: ree
    - rvm: 1.8.7
    - rvm: rbx-18mode
    - rvm: rbx-19mode
branches:
  only:
    - master
